USE mysql;
GRANT ALL PRIVILEGES ON *.* TO '##ENV_MARIA_DB_USER##'@##ENV_MARIA_DB_HOST## WITH GRANT OPTION;
FLUSH PRIVILEGES;
SET PASSWORD FOR '##ENV_MARIA_DB_USER##'@##ENV_MARIA_DB_HOST## = PASSWORD("##ENV_MARIA_DB_PASSWORD##");
CREATE DATABASE IF NOT EXISTS ##ENV_MARIA_DB_DATABASE##;
FLUSH PRIVILEGES;
