#!/usr/bin/env python3
"""
This part of code is taken from:
   https://web.archive.org/web/20160305151936/http://www.jejik.com/articles/2007/02/a_simple_unix_linux_daemon_in_python/
Please respect developer (Sander Marechal) and always keep a reference to URL and also as kudos to him
Changes applied to this code:
    Dedention (Justas Balcas 07/12/2017)
    pylint fixes: with open, split imports, var names, old style class (Justas Balcas 07/12/2017)
"""
import sys
from DTNRMLibs.Daemonizer import Daemon
from DTNRMAgent.RecurringActions.DTNMain import RecurringAction

COMPONENT = 'Agent'
DAEMON = None

class MyDaemon(Daemon):
    """ My own Deamon override """

    def getThreads(self):
        """Multi threading. Allow multiple sites under single FE"""
        outThreads = {}
        for sitename in self.config.get('general', 'sitename').split(','):
            recAgent = RecurringAction(self.config)
            outThreads[sitename] = recAgent
        return outThreads

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print('ERROR: Options available: %s ' % Daemon.ALLCMD)
        sys.exit(1)
    if sys.argv[1] in Daemon.ALLCMD:
        if sys.argv[1] == 'startforeground':
            DAEMON = MyDaemon(COMPONENT, 'StreamLogger')
        else:
            DAEMON = MyDaemon(COMPONENT)
        DAEMON.command(sys.argv[1])
