#!/usr/bin/env python
"""
This part of code is taken from:
   https://web.archive.org/web/20160305151936/http://www.jejik.com/articles/2007/02/a_simple_unix_linux_daemon_in_python/
Please respect developer (Sander Marechal) and always keep a reference to URL and also as kudos to him
Changes applied to this code:
    Dedention (Justas Balcas 07/12/2017)
    pylint fixes: with open, split imports, var names, old style class (Justas Balcas 07/12/2017)
"""
import sys
import time
from DTNRMLibs.Daemonizer import Daemon
from DTNRMLibs.MainUtilities import getLogger
from DTNRMLibs.MainUtilities import getConfig
from SiteFE.ProvisioningService import provisioningService as prsS

CONFIG = getConfig(["/etc/dtnrm-site-fe.conf"])
COMPONENT = 'ProvisioningService'
LOGGER = getLogger("%s/%s/" % (CONFIG.get('general', 'logDir'), COMPONENT), CONFIG.get(COMPONENT, 'logLevel'))



class MyDaemon(Daemon):
    """ My own Deamon override """
    def run(self):
        """ Run main execution """
        provisioner = prsS.ProvisioningService(config=CONFIG, logger=LOGGER, args=None)
        while True:
            try:
                time.sleep(20)
                provisioner.startwork()
            except:
                LOGGER.info('There was uncaught exception')
                excType, excValue = sys.exc_info()[:2]
                LOGGER.critical("Error details. ErrorType: %s, ErrMsg: %s" % (str(excType.__name__), excValue))
                time.sleep(20)

if __name__ == "__main__":
    DAEMON = MyDaemon('/tmp/dtnrm-ProvisioningService.pid')
    if len(sys.argv) == 2:
        DAEMON.command(sys.argv[1], sys.argv[0])
    else:
        DAEMON.command('', sys.argv[0])
