name: "Build FE Containers"

on: # checkov:skip=CKV_GHA_7 User input is controlled and intended for tag/branch selection
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      buildtag:
        description: "Build Tag"
        default: "dev"
        type: "string"
      branch:
        description: "Branch to use of siterm/ansible-collections code?"
        default: "master"
        type: "string"
      sitermbranch:
        description: "Branch to use of siterm/siterm code?"
        default: "master"
        type: "string"
      startupbranch:
        description: "Branch to use of siterm-startup (build base)?"
        default: "master"
        type: "string"

permissions:
  contents: read

concurrency:
  group: build-fe-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      buildtag: ${{ github.event.inputs.buildtag || 'dev' }}
      branch: ${{ github.event.inputs.branch || 'master' }}
      sitermbranch: ${{ github.event.inputs.sitermbranch || 'master' }}
      startupbranch: ${{ github.event.inputs.startupbranch || 'master' }}
    steps:

    - name: Checkout tools repo
      uses: actions/checkout@v5
      with:
        repository: sdn-sense/siterm-startup
        path: siterm-startup
        ref: ${{ env.startupbranch }}

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: docker login quay.io
      env:
        QUAY_USER: ${{secrets.QUAY_USER}}
        QUAY_PASSWORD: ${{secrets.QUAY_PASSWORD}}
      run: docker login quay.io -u $QUAY_USER -p $QUAY_PASSWORD 

    - name: Build the BASE Docker image
      run: | 
        cd siterm-startup/helpers/base_images/fe/
        docker build . --file Dockerfile --build-arg ARCH=amd64 \
         --tag sdnsense/sitermfebase:${{ env.buildtag }} \
         --tag sdnsense/sitermfebase:${{ env.buildtag }}-$(date +%Y%m%d) \
         --tag quay.io/sdnsense/sitermfebase:${{ env.buildtag }} \
         --tag quay.io/sdnsense/sitermfebase:${{ env.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push BASE Image to DockerHub
      run: | 
        docker push sdnsense/sitermfebase:${{ env.buildtag }}
        docker push sdnsense/sitermfebase:${{ env.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push BASE Image to Quay.io
      run: | 
        docker push quay.io/sdnsense/sitermfebase:${{ env.buildtag }}
        docker push quay.io/sdnsense/sitermfebase:${{ env.buildtag }}-$(date +%Y%m%d)

    - name: Build the FE Docker image
      run: | 
        cd siterm-startup/fe/container-build-files/
        docker build . --file Dockerfile \
         --build-arg RELEASE=${{ env.buildtag }} \
         --build-arg GITBR=${{ env.sitermbranch }} \
         --build-arg GITBRANS=${{ env.branch }} \
         --tag sdnsense/siterm-fe:${{ env.buildtag }} \
         --tag sdnsense/siterm-fe:${{ env.buildtag }}-$(date +%Y%m%d) \
         --tag quay.io/sdnsense/siterm-fe:${{ env.buildtag }} \
         --tag quay.io/sdnsense/siterm-fe:${{ env.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push FE Image with tag and date
      run: |
        docker push sdnsense/siterm-fe:${{ env.buildtag }}
        docker push sdnsense/siterm-fe:${{ env.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push FE Image to Quay.io
      run: |
        docker push quay.io/sdnsense/siterm-fe:${{ env.buildtag }}
        docker push quay.io/sdnsense/siterm-fe:${{ env.buildtag }}-$(date +%Y%m%d)
