name: "[QUAY] Debugger EL10"

on: # checkov:skip=CKV_GHA_7 User input is controlled and intended for tag/branch selection
  workflow_dispatch:
    inputs:
      buildtag:
        description: "Build Tag"
        default: "dev"
        type: "string"
      branch:
        description: "Branch to use of siterm code?"
        default: "master"
        type: "string"
      startupbranch:
        description: "Branch to use of siterm-startup (build base)?"
        default: "master"
        type: "string"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: sdn-sense/siterm-startup
        path: siterm-startup
        ref: ${{ github.event.inputs.startupbranch }}

    - name: docker login quay.io
      env:
        QUAY_USER: ${{secrets.QUAY_USER}}
        QUAY_PASSWORD: ${{secrets.QUAY_PASSWORD}}
      run: docker login quay.io -u $QUAY_USER -p $QUAY_PASSWORD 

    - name: Build the BASE Docker image
      run: | 
        cd siterm-startup/helpers/base_images/agent/
        docker build . --file Dockerfile-el10 --tag sdnsense/sitermdebugbase:temp-tag

    - name: Tag BASE image with multiple tags
      run: |
        docker tag quay.io/sdnsense/sitermdebugbase:temp-tag quay.io/sdnsense/sitermdebugbase:${{ github.event.inputs.buildtag }}
        docker tag quay.io/sdnsense/sitermdebugbase:temp-tag quay.io/sdnsense/sitermdebugbase:${{ github.event.inputs.buildtag }}-el10
        docker tag quay.io/sdnsense/sitermdebugbase:temp-tag quay.io/sdnsense/sitermdebugbase:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)
        docker tag quay.io/sdnsense/sitermdebugbase:temp-tag quay.io/sdnsense/sitermdebugbase:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)-el10

    - name: Push BASE image with multiple tags
      run: |
        docker push quay.io/sdnsense/sitermdebugbase:${{ github.event.inputs.buildtag }}
        docker push quay.io/sdnsense/sitermdebugbase:${{ github.event.inputs.buildtag }}-el10
        docker push quay.io/sdnsense/sitermdebugbase:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)
        docker push quay.io/sdnsense/sitermdebugbase:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)-el10

    - name: Build the Debugger Service Docker image
      run: |
        cd siterm-startup/debugger/container-build-files/
        docker build . --file Dockerfile-el10 --build-arg RELEASE=${{ github.event.inputs.buildtag }} --build-arg GITBR=${{ github.event.inputs.branch }} --tag quay.io/sdnsense/siterm-debugger:temp-tag

    - name: Tag Debugger image with multiple tags
      run: |
        docker tag quay.io/sdnsense/siterm-debugger:temp-tag quay.io/sdnsense/siterm-debugger:${{ github.event.inputs.buildtag }}
        docker tag quay.io/sdnsense/siterm-debugger:temp-tag quay.io/sdnsense/siterm-debugger:${{ github.event.inputs.buildtag }}-el10
        docker tag quay.io/sdnsense/siterm-debugger:temp-tag quay.io/sdnsense/siterm-debugger:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)
        docker tag quay.io/sdnsense/siterm-debugger:temp-tag quay.io/sdnsense/siterm-debugger:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)-el10

    - name: Push Debugger image with multiple tags
      run: |
        docker push quay.io/sdnsense/siterm-debugger:${{ github.event.inputs.buildtag }}
        docker push quay.io/sdnsense/siterm-debugger:${{ github.event.inputs.buildtag }}-el10
        docker push quay.io/sdnsense/siterm-debugger:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)
        docker push quay.io/sdnsense/siterm-debugger:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)-el10