name: "[QUAY] FE"

on: # checkov:skip=CKV_GHA_7 User input is controlled and intended for tag/branch selection
  workflow_dispatch:
    inputs:
      buildtag:
        description: "Build Tag"
        default: "dev"
        type: "string"
      branch:
        description: "Branch to use of siterm/ansible-collections code?"
        default: "master"
        type: "string"
      sitermbranch:
        description: "Branch to use of siterm/siterm code?"
        default: "master"
        type: "string"
      startupbranch:
        description: "Branch to use of siterm-startup (build base)?"
        default: "master"
        type: "string"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: sdn-sense/siterm-startup
        path: siterm-startup
        ref: ${{ github.event.inputs.startupbranch }}

    - name: docker login quay.io
      env:
        QUAY_USER: ${{secrets.QUAY_USER}}
        QUAY_PASSWORD: ${{secrets.QUAY_PASSWORD}}
      run: docker login quay.io -u $QUAY_USER -p $QUAY_PASSWORD 

    - name: Build the BASE Docker image
      run: | 
        cd siterm-startup/helpers/base_images/fe/
        docker build . --file Dockerfile --build-arg ARCH=amd64 --tag quay.io/sdnsense/sitermfebase:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push BASE Image with tag and date
      run: docker push quay.io/sdnsense/sitermfebase:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push BASE Image with tag
      run: |
        docker tag quay.io/sdnsense/sitermfebase:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d) quay.io/sdnsense/sitermfebase:${{ github.event.inputs.buildtag }}
        docker push quay.io/sdnsense/sitermfebase:${{ github.event.inputs.buildtag }}

    - name: Build the FE Docker image
      run: | 
        cd siterm-startup/fe/container-build-files/
        docker build . --file Dockerfile --build-arg RELEASE=${{ github.event.inputs.buildtag }} --build-arg GITBR=${{ github.event.inputs.sitermbranch }} --build-arg GITBRANS=${{ github.event.inputs.branch }} --tag quay.io/sdnsense/siterm-fe:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push FE Image with tag and date
      run: docker push quay.io/sdnsense/siterm-fe:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d)

    - name: Docker Push FE Image with tag
      run: |
        docker tag quay.io/sdnsense/siterm-fe:${{ github.event.inputs.buildtag }}-$(date +%Y%m%d) quay.io/sdnsense/siterm-fe:${{ github.event.inputs.buildtag }}
        docker push quay.io/sdnsense/siterm-fe:${{ github.event.inputs.buildtag }}
