name: Build SiteRM Debugger Container (EL10)

on: # checkov:skip=CKV_GHA_7 User input is controlled and intended for tag/branch selection
  workflow_dispatch:
    inputs:
      buildtag:
        description: "Build Tag"
        default: "dev"
        type: "string"
      branch:
        description: "Branch to use of siterm code?"
        default: "master"
        type: "string"
      startupbranch:
        description: "Branch to use of siterm-startup (build base)?"
        default: "master"
        type: "string"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: sdn-sense/siterm-startup
        path: siterm-startup
        ref: ${{ github.event.inputs.startupbranch }}

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 

    - name: Build the BASE Docker image
      run: | 
        cd siterm-startup/helpers/base_images/agent/
        docker build . --file Dockerfile-el10 --tag sdnsense/sitermdebugbase:temp-tag

    - name: Tag BASE image with multiple tags
      run: |
        DATE=$(date +%Y%m%d)
        docker tag sdnsense/sitermdebugbase:temp-tag sdnsense/sitermdebugbase:${{ github.event.inputs.buildtag }}
        docker tag sdnsense/sitermdebugbase:temp-tag sdnsense/sitermdebugbase:${{ github.event.inputs.buildtag }}-${DATE}
        docker tag sdnsense/sitermdebugbase:temp-tag sdnsense/sitermdebugbase:${{ github.event.inputs.buildtag }}-${DATE}-el10

    - name: Push BASE image with multiple tags
      run: |
        DATE=$(date +%Y%m%d)
        docker push sdnsense/sitermdebugbase:${{ github.event.inputs.buildtag }}
        docker push sdnsense/sitermdebugbase:${{ github.event.inputs.buildtag }}-${DATE}
        docker push sdnsense/sitermdebugbase:${{ github.event.inputs.buildtag }}-${DATE}-el10

    - name: Build the Debugger Service Docker image
      run: |
        cd siterm-startup/debugger/container-build-files/
        docker build . --file Dockerfile-el10 --build-arg RELEASE=${{ github.event.inputs.buildtag }} --build-arg GITBR=${{ github.event.inputs.branch }} --tag sdnsense/siterm-debugger:temp-tag

    - name: Tag Debugger image with multiple tags
      run: |
        DATE=$(date +%Y%m%d)
        docker tag sdnsense/siterm-debugger:temp-tag sdnsense/siterm-debugger:${{ github.event.inputs.buildtag }}
        docker tag sdnsense/siterm-debugger:temp-tag sdnsense/siterm-debugger:${{ github.event.inputs.buildtag }}-${DATE}
        docker tag sdnsense/siterm-debugger:temp-tag sdnsense/siterm-debugger:${{ github.event.inputs.buildtag }}-${DATE}-el10

    - name: Push Debugger image with multiple tags
      run: |
        DATE=$(date +%Y%m%d)
        docker push sdnsense/siterm-debugger:${{ github.event.inputs.buildtag }}
        docker push sdnsense/siterm-debugger:${{ github.event.inputs.buildtag }}-${DATE}
        docker push sdnsense/siterm-debugger:${{ github.event.inputs.buildtag }}-${DATE}-el10