#!/usr/bin/env python3
"""
This part of code is taken from:
   https://web.archive.org/web/20160305151936/http://www.jejik.com/articles/2007/02/a_simple_unix_linux_daemon_in_python/
Please respect developer (Sander Marechal) and always keep a reference to URL and also as kudos to him
Changes applied to this code:
    Dedention (Justas Balcas 07/12/2017)
    pylint fixes: with open, split imports, var names, old style class (Justas Balcas 07/12/2017)
"""
import sys
from SiteRMLibs.Daemonizer import Daemon, getParser, validateArgs
try:
    from SiteRMAgent.Debugger import Debugger
except (ImportError, ModuleNotFoundError):
    from SiteFE.Debugger import Debugger

COMPONENT = 'Debugger'
DESCRIPTION = "Debugger start's debug process, like ping, iperf, tcpdump, arp on the agent node"
DAEMON = None

class MyDaemon(Daemon):
    """ My own Deamon override """

    def getThreads(self, houreq, dayeq):
        """Multi threading. Allow multiple sites under single FE"""
        sites = []
        if self.config.has_option('general', "sites"):
            sites = self.config.get('general', 'sites')
        elif self.config.has_option('general', "sitename"):
            sites = self.config.get('general', 'sitename')
        else:
            raise ValueError("No sites defined in config file. Fatal Failure")
        for sitename in sites:
            if sitename not in self.runThreads:
                debAgent = Debugger.Debugger(self.config, sitename)
                self.runThreads[sitename] = debAgent
            self.runThreads[sitename].refreshthread(houreq, dayeq)

if __name__ == "__main__":
    parser = getParser(DESCRIPTION)
    if len(sys.argv) == 1:
        parser.print_help()
    inargs = parser.parse_args(sys.argv[1:])
    validateArgs(inargs)
    DAEMON = MyDaemon(COMPONENT, inargs)
    DAEMON.command()
