#!/usr/bin/env python3
"""
Kubernetes readiness checker for the pod.
"""
import sys
from os import walk
from SiteRMLibs.MainUtilities import getFileContentAsJson


def getStates():
    """Get the states of all services and return the exit code"""
    directory = '/tmp/siterm-states/'
    files = []
    exitCode = 0
    for (_, _, filenames) in walk(directory):
        files.extend(filenames)
        break
    for fname in files:
        if fname.endswith('.json'):
            out = getFileContentAsJson(directory + fname)
            if out.get('state', 'UNKNOWN') != 'OK':
                exitCode = 1
                print("State for service is not OK. Details: ", fname, out)
    return exitCode

if __name__ == "__main__":
    state = getStates()
    sys.exit(state)
